# Generated by Django 4.1.7 on 2023-06-27 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название крупной задачи')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('started_at_date', models.DateField(default=django.utils.timezone.localtime, verbose_name='Дата начала')),
                ('started_at_time', models.TimeField(default=django.utils.timezone.localtime, verbose_name='Время начала')),
                ('due_date_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('due_date_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('status', models.IntegerField(choices=[(0, 'Запланировано'), (1, 'В процессе'), (2, 'Выполнено')], default=0)),
            ],
            options={
                'verbose_name': 'большая задача',
                'verbose_name_plural': 'большие задачи',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('started_at_date', models.DateField(default=django.utils.timezone.localtime, verbose_name='Дата начала')),
                ('started_at_time', models.TimeField(default=django.utils.timezone.localtime, verbose_name='Время начала')),
                ('due_date_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('due_date_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('order_in_big_task', models.IntegerField(blank=True, default=0, null=True, verbose_name='Приоритетность')),
                ('status', models.IntegerField(choices=[(0, 'Запланировано'), (1, 'В процессе'), (2, 'Выполнено')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ['-created_at'],
            },
        ),
    ]
