# Generated by Django 4.1.7 on 2023-04-12 10:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='todo.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('started_at_date', models.DateField(default=datetime.date(2023, 4, 12), verbose_name='Дата начала')),
                ('started_at_time', models.TimeField(default=datetime.datetime(2023, 4, 12, 10, 41, 37, 409662, tzinfo=datetime.timezone.utc), verbose_name='Время начала')),
                ('due_date_date', models.DateField(verbose_name='Дата окончания')),
                ('due_date_time', models.TimeField(verbose_name='Время окончания')),
                ('order_in_big_task', models.IntegerField(blank=True, default=0, null=True, verbose_name='Приоритетность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='BigTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название крупной задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('started_at_date', models.DateField(default=datetime.date(2023, 4, 12), verbose_name='Дата начала')),
                ('started_at_time', models.TimeField(default=datetime.datetime(2023, 4, 12, 10, 41, 37, 409662, tzinfo=datetime.timezone.utc), verbose_name='Время начала')),
                ('due_date_date', models.DateField(verbose_name='Дата окончания')),
                ('due_date_time', models.TimeField(verbose_name='Время окончания')),
                ('body', models.ManyToManyField(related_name='tasks', to='todo.task', verbose_name='Подзадачи')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.category', verbose_name='Категория')),
            ],
        ),
    ]
