# Generated by Django 4.1.7 on 2023-06-27 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='todo.category'),
        ),
        migrations.AddField(
            model_name='bigtask',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='bigtask',
            name='body',
            field=models.ManyToManyField(related_name='tasks', to='todo.task', verbose_name='Подзадачи'),
        ),
        migrations.AddField(
            model_name='bigtask',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.category', verbose_name='Категория'),
        ),
    ]
