# Generated by Django 4.1.7 on 2023-04-12 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigtask',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Описание задачи'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='bigtask',
            name='started_at_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='bigtask',
            name='started_at_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='task',
            name='started_at_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='task',
            name='started_at_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время начала'),
        ),
    ]
