# Generated by Django 4.1.7 on 2023-04-27 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_bigtask_description_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigtask',
            name='due_date_date',
            field=models.DateField(blank=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='bigtask',
            name='due_date_time',
            field=models.TimeField(blank=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='bigtask',
            name='started_at_date',
            field=models.DateField(default=django.utils.timezone.localtime, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='bigtask',
            name='started_at_time',
            field=models.TimeField(default=django.utils.timezone.localtime, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date_date',
            field=models.DateField(blank=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date_time',
            field=models.TimeField(blank=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='started_at_date',
            field=models.DateField(default=django.utils.timezone.localtime, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='task',
            name='started_at_time',
            field=models.TimeField(default=django.utils.timezone.localtime, verbose_name='Время начала'),
        ),
    ]
