# Generated by Django 4.1.7 on 2023-05-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_bigtask_due_date_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigtask',
            name='status',
            field=models.IntegerField(choices=[(0, 'Запланировано'), (1, 'В процессе'), (2, 'Выполнено')], default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Запланировано'), (1, 'В процессе'), (2, 'Выполнено')], default=0),
        ),
    ]
